
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author invitado
 */
public class BLOCK_DE_NOTAS extends javax.swing.JFrame {

    /**
     * Creates new form BLOCK_DE_NOTAS
     */
    public BLOCK_DE_NOTAS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtABlockNotas = new javax.swing.JTextArea();
        txtAbuttonAbrir = new javax.swing.JButton();
        txtAbuttonGuardar = new javax.swing.JButton();
        txtAbuttonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtABlockNotas.setColumns(20);
        txtABlockNotas.setRows(5);
        jScrollPane1.setViewportView(txtABlockNotas);

        txtAbuttonAbrir.setText("Abrir");
        txtAbuttonAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAbuttonAbrirMouseClicked(evt);
            }
        });
        txtAbuttonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAbuttonAbrirActionPerformed(evt);
            }
        });

        txtAbuttonGuardar.setText("Guardar");
        txtAbuttonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAbuttonGuardarMouseClicked(evt);
            }
        });

        txtAbuttonCerrar.setText("Cerrar");
        txtAbuttonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAbuttonCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAbuttonGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAbuttonAbrir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAbuttonCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtAbuttonAbrir)
                .addGap(18, 18, 18)
                .addComponent(txtAbuttonGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(txtAbuttonCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAbuttonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAbuttonAbrirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAbuttonAbrirActionPerformed

    private void txtAbuttonAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAbuttonAbrirMouseClicked
        // TODO add your handling code here:
        
        System.out.println("Si jala el abrir");
        JFileChooser fileChooser=new JFileChooser("C:\\apps\\");
        int resu=fileChooser.showOpenDialog(this);
        
        BufferedReader bufferedReader=null;
        InputStreamReader isReader=null;
        if(resu==JFileChooser.APPROVE_OPTION){
            try {
            //abrio el archivo
            
            InputStream in;
            
            Path path=fileChooser.getSelectedFile().toPath();
            
            in=Files.newInputStream(path);
            
            
            
            isReader=new InputStreamReader(in);
            
            
            bufferedReader=new BufferedReader(isReader);
            txtABlockNotas.read(bufferedReader, "Abrir archivo...");
            
            
            } catch (IOException ex) {
                Logger.getLogger(BLOCK_DE_NOTAS.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    bufferedReader.close();
                    isReader.close();
                } catch (IOException ex) {
                    Logger.getLogger(BLOCK_DE_NOTAS.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_txtAbuttonAbrirMouseClicked

    private void txtAbuttonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAbuttonGuardarMouseClicked
        // TODO add your handling code here:
        System.out.println("Si jala el guardar");
    }//GEN-LAST:event_txtAbuttonGuardarMouseClicked

    private void txtAbuttonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAbuttonCerrarMouseClicked
        // TODO add your handling code here:
        
        System.exit(0);//cierra
    }//GEN-LAST:event_txtAbuttonCerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BLOCK_DE_NOTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BLOCK_DE_NOTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BLOCK_DE_NOTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BLOCK_DE_NOTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BLOCK_DE_NOTAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtABlockNotas;
    private javax.swing.JButton txtAbuttonAbrir;
    private javax.swing.JButton txtAbuttonCerrar;
    private javax.swing.JButton txtAbuttonGuardar;
    // End of variables declaration//GEN-END:variables
}
